spring:
 application:
  name: "configserver"
 profiles:
  #active: native
  active: git
 cloud:
  config:
   server:
    #native:
     #search-locations: "classpath:/config"
     #search-locations: "file:///Users//admin//Desktop//yesbankconfig"
    git: 
     uri: "https://github.com/Wilson390/yesconf"
     default-label: main
     timeout: 5
     clone-on-start: true
     force-pull: true
management:
 endpoints:
  web:
   exposure:
    include: "*"
 health:
  readiness-state:
   enabled: true
  liveness-state:
   enabled: true
 endpoint:
  health:
   probes:
    enabled: true
  
encrypt:
 key: "GFG768HJGJGWAFDGHKLPO906543"

server:
  port: 8071